### ISSUE TITLE
Wrong heuristics with BMW M2

### ISSUE THREAD

**Issue by maxbechtold** [soong-construction/dirt-rally-time-recorder#40]
> i have the first error case. here is the output from the time recorder:
> 
> ```
> TRACK: Camino a La Puerta
> Ambiguous car data, 2 matches
> Mitsubishi Lancer Evolution VI: H-PATTERN shifting, 6 speed, with HANDBRAKE
> BMW M2 Competition: SEQUENTIAL shifting, 6 speed, with HANDBRAKE
> Guessing car...
> CAR: Mitsubishi Lancer Evolution VI
> If heuristics-based guess IS WRONG, RUN THE SCRIPT provided to fix the recorded car:
>  ==> 1589311053_CaminoaLaPuerta_BMWM2Competition.bat
> Completed stage in 06:51.820.
> ```
> 
> It actually was the BMW M2. I'm playing with gamepad and manual sequential shifting. I guess, the heuristic should be able to find this case.
> I uploaded the run logged with my tool: [gdrive](https://drive.google.com/file/d/154Q9OtaKa-E6XKV1Jn-YOMfQe1LFLlP4/view?usp=sharing)
> You can open it with my tool or simply with numpy.load() and see if you can find a reason for the wrong heuristic.

Thanks for reporting @ErlerPhilipp! Can you also share the timerecord.log of that day and the heuristics config? I should look into it.

**Comment by ErlerPhilipp** [comment]
[timerecord.log](https://drive.google.com/file/d/1fukVs-qtl1v99YcFy40mgPVqvqS9IP9X/view?usp=sharing)

if you mean config.yml by heuristics config:
heuristics:
  activate: 1
  authentic_shifting: 0
keep_update_scripts_days: 50
show_car_controls: 1
speed_unit: kph
telemetry_server:
  host: 127.0.0.1
  port: 20776

not sure if i correctly set the authentic_shifting to 0

**Comment by maxbechtold** [comment]
Yes indeed I meant `config.yml`, sorry. 

Ah! Since you did not enable authentic_shifting (by setting it to 1) it will only use a lucky guess and therefore does not consider your shifting input. 

For this car, you can test authentic_shifting - with sequential shifting it should guess the M2 correctly. 
But in general of course, authentic_shifting will not work for you on a gamepad. Do you think I should make the docs more clear about that?

**Comment by ErlerPhilipp** [comment]
Now with authentic_shifting = 1:
```
Starting dirt-rally-time-recorder 2.7.0
HEURISTICS activated
Found 156 tracks and 56 cars
Checking laptimes database
Waiting for data on 127.0.0.1:20776
TRACK: Naarajärvi
Ambiguous car data, 2 matches
Mitsubishi Lancer Evolution VI: H-PATTERN shifting, 6 speed, with HANDBRAKE
BMW M2 Competition: SEQUENTIAL shifting, 6 speed, with HANDBRAKE
Guessing car...
CAR: BMW M2 Competition
If heuristics-based guess IS WRONG, RUN THE SCRIPT provided to fix the recorded car:
 ==> 1589488835_Naarajärvi_MitsubishiLancerEvolutionVI.bat
Completed stage in 03:36.674.
TRACK: Tsiristra Théa
Ambiguous car data, 2 matches
Mitsubishi Lancer Evolution VI: H-PATTERN shifting, 6 speed, with HANDBRAKE
BMW M2 Competition: SEQUENTIAL shifting, 6 speed, with HANDBRAKE
Guessing car...
CAR: BMW M2 Competition
If heuristics-based guess IS WRONG, RUN THE SCRIPT provided to fix the recorded car:
 ==> 1589489539_TsiristraThéa_MitsubishiLancerEvolutionVI.bat
Completed stage in 07:12.052.
```

As expected, it guesses the BMW M2 in both cases. I guess, it works then.

**Comment by maxbechtold** [comment]
Great, then I guess this issue can be closed, but feel free to comment. By the way, I have requested access to the files you shared via Google Drive, but it looks like you need to still grant it.

Just to be clear to readers, your use case does not warrant the authentic_shifting heuristics. I do however work on user signals that can be used as an additional heuristics that will also work for keyboard players, see #25. Or if you have about 50 EUR to spare... a used Logitech wheel should greatly improve immersion :)
